//! T048 — Generate `OUT_DIR/rules_1000.epd` (≥1000 unique FENs) for SC-008.
//!
//! Seeds from `crates/chess-core/tests/corpora/rules_v1.epd`, then BFS over
//! `chess_core` legal moves until 1000 positions. Every line is tagged with
//! `lm`, `chk`, and `term` expected values: `lm`/`chk` are cross-checked against
//! `cozy-chess` during generation; `term` follows the same priority as
//! `tests/rules.rs` / `Game::detect_result` (excluding threefold, which needs
//! history).

use std::collections::{HashMap, HashSet, VecDeque};
use std::fs;
use std::path::Path;

use chess_core::is_in_check;
use chess_core::legal_moves;
use chess_core::position::Position;
use chess_core::rules::{is_fifty_move, is_insufficient_material, is_threefold};
use cozy_chess::Board;

#[derive(Debug, Clone, PartialEq, Eq)]
enum Term {
    None,
    Mate,
    Stalemate,
    Fifty,
    Insufficient,
}

impl Term {
    fn as_str(&self) -> &'static str {
        match self {
            Term::None => "none",
            Term::Mate => "mate",
            Term::Stalemate => "stalemate",
            Term::Fifty => "fifty",
            Term::Insufficient => "insufficient",
        }
    }
}

fn classify_term(pos: &Position) -> Term {
    let legal = legal_moves(pos);
    if legal.is_empty() {
        return if is_in_check(pos) {
            Term::Mate
        } else {
            Term::Stalemate
        };
    }
    let empty: HashMap<u64, u8> = HashMap::new();
    debug_assert!(!is_threefold(&empty, pos));
    if is_fifty_move(pos) {
        return Term::Fifty;
    }
    if is_insufficient_material(pos) {
        return Term::Insufficient;
    }
    Term::None
}

fn cozy_legal_count(board: &Board) -> usize {
    let mut n = 0usize;
    board.generate_moves(|moves| {
        n += moves.len();
        false
    });
    n
}

/// Clamp the FEN halfmove-clock field to 99 so cozy-chess accepts the
/// position. Halfmove only governs the 50-move draw rule, not move
/// generation, so the resulting board is identical for legal-moves /
/// in-check oracle comparisons.
fn clamp_halfmove_for_cozy(fen: &str) -> String {
    let parts: Vec<&str> = fen.split_whitespace().collect();
    if parts.len() < 5 {
        return fen.to_string();
    }
    let hm: u32 = parts[4].parse().unwrap_or(0);
    if hm < 100 {
        return fen.to_string();
    }
    let mut out = parts.clone();
    out[4] = "99";
    out.join(" ")
}

fn extract_fens_from_v1(text: &str) -> Vec<String> {
    let mut out = Vec::new();
    for raw in text.lines() {
        let t = raw.trim();
        if t.is_empty() || t.starts_with('#') {
            continue;
        }
        let fen = t.split(';').next().unwrap_or("").trim();
        if !fen.is_empty() {
            out.push(fen.to_string());
        }
    }
    out
}

fn main() {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let manifest_dir_var =
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let manifest_dir = Path::new(&manifest_dir_var);

    let v1_path = manifest_dir.join("crates/chess-core/tests/corpora/rules_v1.epd");
    let v1_text =
        fs::read_to_string(&v1_path).unwrap_or_else(|e| panic!("read {}: {e}", v1_path.display()));

    let mut seen_fen: HashSet<String> = HashSet::new();
    let mut collected: Vec<Position> = Vec::new();
    let mut queue: VecDeque<Position> = VecDeque::new();

    for fen in extract_fens_from_v1(&v1_text) {
        if let Ok(p) = Position::from_fen(&fen) {
            let k = p.to_fen();
            if seen_fen.insert(k) {
                collected.push(p.clone());
                queue.push_back(p);
            }
        }
    }

    let start = Position::startpos();
    let k = start.to_fen();
    if seen_fen.insert(k) {
        collected.push(start.clone());
        queue.push_back(start);
    }

    while collected.len() < 1000 {
        let Some(pos) = queue.pop_front() else {
            panic!(
                "rules_1000: BFS exhausted before 1000 positions (got {}). \
                 Lower branching or add seeds.",
                collected.len()
            );
        };

        for mv in legal_moves(&pos) {
            if collected.len() >= 1000 {
                break;
            }
            let (child, _) = pos.make_move(mv);
            let key = child.to_fen();
            if seen_fen.insert(key) {
                collected.push(child.clone());
                queue.push_back(child);
            }
        }
    }

    let dest = Path::new(&out_dir).join("rules_1000.epd");
    let mut w = String::new();
    w.push_str("# T048 — rules_1000.epd (generated by build.rs)\n");
    w.push_str("# ≥1000 positions: curated v1 seeds + BFS expansion; tags validated vs cozy-chess.\n\n");

    for (i, pos) in collected.iter().enumerate() {
        let fen = pos.to_fen();
        // cozy-chess rejects halfmove clocks >= 100. Clamp purely for the
        // cozy oracle round-trip; halfmove does not affect legal-move
        // generation or check status, so the comparison is still meaningful.
        let cozy_fen = clamp_halfmove_for_cozy(&fen);
        let cz = Board::from_fen(&cozy_fen, false)
            .unwrap_or_else(|e| panic!("cozy FEN {cozy_fen}: {e}"));
        let lm_ours = legal_moves(pos).len();
        let lm_cz = cozy_legal_count(&cz);
        assert_eq!(
            lm_ours, lm_cz,
            "legal move count mismatch (chess-core vs cozy) at {fen}"
        );
        let chk_ours = is_in_check(pos);
        let chk_cz = !cz.checkers().is_empty();
        assert_eq!(
            chk_ours, chk_cz,
            "in-check mismatch (chess-core vs cozy) at {fen}"
        );

        let term = classify_term(pos);
        w.push_str(&format!(
            "{} ; lm {} ; chk {} ; term {} ; cat \"bfs-oracle\" ; id \"GEN.{:04}\"\n",
            fen,
            lm_ours,
            if chk_ours { "yes" } else { "no" },
            term.as_str(),
            i + 1
        ));
    }

    fs::write(&dest, w).unwrap_or_else(|e| panic!("write {}: {e}", dest.display()));
    println!("cargo:warning=generated {} with {} lines", dest.display(), collected.len());
}
