apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chess-app.fullname" . }}
  labels:
    {{- include "chess-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chess-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chess-app.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "chess-app.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        env:
        - name: CHESS_AI_STORAGE_PATH
          value: "/mnt/s3/ai-models"
        - name: AWS_REGION
          value: {{ .Values.s3.region }}
        - name: SPRING_PROFILES_ACTIVE
          value: {{ .Values.global.environment | default "prod" }}
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        volumeMounts:
        - name: secrets-store
          mountPath: "/mnt/secrets"
          readOnly: true
        - name: ai-models-storage
          mountPath: "/mnt/s3/ai-models"
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "chess-app-secrets"
      - name: ai-models-storage
        csi:
          driver: s3.csi.aws.com
          volumeAttributes:
            bucketName: {{ .Values.s3.bucket }}
            region: {{ .Values.s3.region }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}